DROP TABLE IF EXISTS cities;
DROP TABLE IF EXISTS person;
CREATE TABLE cities(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100),population INT);
CREATE TABLE person(id bigint(20) NOT NULL AUTO_INCREMENT,name varchar(50) DEFAULT NULL,PRIMARY KEY (id));